app/analyse/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from wtforms.validators import DataRequired


class ChartForm(FlaskForm):
    """
    Form for users to add new energy bill
    """
    year = SelectField('Okres', validators=[DataRequired()], choices=[("2015", "2015"), ("2016", "2016"),
                                                                      ("2017", "2017"), ("2018", "2018"),
                                                                      ("2019", "2019"), ("All", "Wszystkie"),
                                                                      ('Avarage', 'Średnia')])
    building = SelectField('Budynek', validators=[DataRequired()], choices=[("SCH", "Szkoła"), ("WOR", "Warsztat"),
                                                                            ("All", "Wszystkie")])
    energy_type = SelectField('Rodzaj energii', validators=[DataRequired()],
                              choices=[("energy", "Energia elektryczna"), ("gas", "Gaz"),
                                       ("All", "Wszystkie")])
    chart_type = SelectField('Typ wykresu', validators=[DataRequired()],
                             choices=[("Column", "Kolumnowy"), ("Line", "Liniowy"),
                                      ("Surface", "Powierzchniowy")])
    submit = SubmitField('Wygeneruj wykres')

    # TODO: validators

app/analyse/__init__.py
from flask import Blueprint


analyse = Blueprint('analyse', __name__)


from app.analyse import views

app/analyse/views.py
from flask import render_template
from flask_login import login_required

from app.analyse import analyse
from app.analyse.forms import ChartForm
from app.analyse.chart_tool import ChartTool
from bokeh.embed import components


@analyse.route('/analyse', methods=['GET', 'POST'])
@login_required
def show():
    """
     Handle requests to the /show route
     Displays chart based on form
    """

    form = ChartForm()
    building = 'SCH'
    year = 2017
    energy_type = 'energy'
    chart_type = 'Column'
    if form.validate_on_submit():
        year = form.year.data
        building = form.building.data
        energy_type = form.energy_type.data
        chart_type = form.chart_type.data

    chart = ChartTool(building=building, interval=year, energy_type=energy_type, chart_type=chart_type)
    script, div = components(chart.plot)

    return render_template("analyse.html", the_div=div, the_script=script, form=form)

app/templates/add_energy.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}Dodaj energię{% endblock %}

{% block header %}
<div class="content-section">
    <div class="center">
        <br/>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}


{% block content %}
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#ccc;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#f0f0f0;}
.tg .tg-0lax{text-align:left;vertical-align:top}



</style>
<table class="tg">
    <caption style="font-size:25px">Ostatnie rachunki:</caption>
    <tr>
        <th class="tg-0lax">Rok</th>
        <th class="tg-0lax">Miesiąc</th>
        <th class="tg-0lax">Budynek</th>
        <th class="tg-0lax">Zużycie energii [kWh]<br></th>
        <th class="tg-0lax">Cena za zużycie [zł]</th>
        <th class="tg-0lax">Cena za przesył [zł]</th>
    </tr>
    {% for row in rows %}

    <tr>
        <td>{{ row[0] }}</a></td>
        <td>{{ row[1] }}</td>
        <td>{{ row[2] }}</a></td>
        <td>{{ row[3] }}</td>
        <td>{{ row[4] }}</a></td>
        <td>{{ row[5] }}</td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

app/templates/add_gas.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}

{% block title %}Dodaj gaz{% endblock %}

{% block header %}
<div class="content-section">
    <div class="center">
        <br/>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}


{% block content %}
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;border-color:#ccc;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#f0f0f0;}
.tg .tg-0lax{text-align:left;vertical-align:top}



</style>
<table class="tg">
    <caption style="font-size:25px">Ostatnie rachunki:</caption>
    <tr>
        <th class="tg-0lax">Rok</th>
        <th class="tg-0lax">Miesiąc</th>
        <th class="tg-0lax">Budynek</th>
        <th class="tg-0lax">Zużycie gazu [m3]<br></th>
        <th class="tg-0lax">Cena gazu [zł]</th>
    </tr>
    {% for row in rows %}

    <tr>
        <td>{{ row[0] }}</a></td>
        <td>{{ row[1] }}</td>
        <td>{{ row[2] }}</a></td>
        <td>{{ row[3] }}</td>
        <td>{{ row[4] }}</td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

app/templates/analyse.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends 'base.html' %}

{% block title %}Analiza{% endblock %}

{% block header %}
<div class="content-section">
    <div class="center">
        <br/>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}


{% block content %}
{{ the_div|safe }}
<script src="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.js"></script>
<script src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.4.min.js"></script>
{{ the_script|safe }}
{% endblock %}

app/templates/base.html
<!doctype html>
<title>{{ title }}</title>
<link href="http://cdn.pydata.org/bokeh/release/bokeh-1.0.4.min.css" rel="stylesheet">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.0.4.min.css" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet">
<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
<nav>
    <div class="container topnav">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand topnav" >Analiza zużycia energii elektrycznej i gazu</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('data_crud.add_energy') }}">Dodaj energię elektryczną</a></li>
                <li><a href="{{ url_for('data_crud.add_gas') }}">Dodaj gaz</a></li>
                <li><a href="{{ url_for('analyse.show') }}">Analiza</a></li>
            </ul>
        </div>
    </div>
</nav>
<section class="content">
    <header>
        {% block header %}{% endblock %}
    </header>
    {% block content %}{% endblock %}
</section>

app/templates/login.html
{% import "bootstrap/utils.html" as utils %}
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block header %}
<div class="content-section">
  <br/>
  {{ utils.flashed_messages() }}
  <br/>
  <div class="center">
    <h1>Zaloguj się</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}

app/templates/register.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block header %}
<div class="content-section">
  <div class="center">
    <h1>Register for an account</h1>
    <br/>
    {{ wtf.quick_form(form) }}
  </div>
</div>
{% endblock %}